language: cpp
compiler:
    - clang
    - gcc
dist: xenial
addons:
    apt:
        packages:
            - python3
            - python3-pip
            - python3-setuptools

before_install:
    - pip3 install -U setuptools
    - pip3 install -U online-judge-tools=='7.2.*'
    - pip3 install -U git+https://github.com/kmyk/online-judge-verify-helper.git@master
script:
    - oj-verify run
